### ISSUE TITLE
QUERY: Check for binding

### ISSUE THREAD

**Issue by nheitz** [proctorlabs/templar#2]
Hello!  I'm quite keen to use this templating approach, particularly on the command line.  After combing the documentation that I can find, however, I cannot determine if there is a mechanism for detecting if a named context value is bound or not.  Is there some mechanism to math on "Some" or "None"?

For instance, I would like to do the following:
```
{% if exists("binary_name") %}
var BINARY_VERSION_UPGRADE = "{{ binary_name }}";
{% end if %}
```

where, obviously, I've made up the "exists" function.  Can I check the presence of a binding?

**Comment by philproctor** [comment]
You're right, that method didn't exist! I added it just now in 0.4.2, here is an example of usage

```
{{ user = 'test' }}
{%- if user | exists %}
You are running as the user {{ user }}
{%- else %}
Your user information isn't available!
{%- end if %}
```
